# Generated by Django 4.0.3 on 2023-11-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0006_rename_u_log_user_id_alter_log_user_id'),
        ('Bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='model_name',
            field=models.ForeignKey(db_column='model_name', on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_model_name', to='Equipments.equipment'),
        ),
    ]
