# Generated by Django 4.0.3 on 2023-11-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
