# Generated by Django 4.0.3 on 2023-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
                ('type', models.CharField(default=None, max_length=30)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('repository', models.CharField(default=None, max_length=30)),
                ('total_rent', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('current_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('manufacturer', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('recommend_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
    ]
