# Generated by Django 4.0.3 on 2023-11-22 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
                ('type', models.CharField(default=None, max_length=30)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('repository', models.CharField(default=None, max_length=30)),
                ('total_rent', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('current_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('manufacturer', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('recommend_count', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('recommend_user', models.ManyToManyField(blank=True, related_name='recommend_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_count', models.IntegerField(default=0)),
                ('return_deadline', models.DateTimeField(blank=True, default=None, null=True)),
                ('rent_requested_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('rent_accepted_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('return_requested_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('return_accepted_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('rent_price', models.IntegerField(blank=True, default=None, null=True)),
                ('model_name', models.ForeignKey(db_column='model_name', on_delete=django.db.models.deletion.CASCADE, to='Equipments.equipment')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
