# Generated by Django 4.0.3 on 2023-11-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
    ]
