# Generated by Django 4.0.3 on 2023-11-24 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Equipments', '0002_returned_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returned',
            name='user_id',
            field=models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, related_name='returned_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
