# Generated by Django 4.0.3 on 2023-11-22 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0002_alter_log_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
