# Generated by Django 4.0.3 on 2023-11-22 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0002_alter_equipment_recommend_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 8, 0)),
        ),
    ]
