# Generated by Django 4.0.3 on 2023-11-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0003_log_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='Log',
        ),
    ]
