# Generated by Django 4.0.3 on 2023-11-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0003_equipment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
