# Generated by Django 4.0.3 on 2023-11-22 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0004_alter_equipment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 8, 0)),
        ),
    ]
