# Generated by Django 4.0.3 on 2023-11-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0004_alter_log_return_accepted_date_returned'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='returned',
            table='returned',
        ),
    ]
