# Generated by Django 4.0.3 on 2023-11-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0004_alter_log_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
    ]
