# Generated by Django 4.0.3 on 2023-11-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0005_equipment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
