# Generated by Django 4.0.3 on 2023-11-23 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Equipments', '0005_alter_returned_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.ForeignKey(db_column='log_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returning_log_id', to='Equipments.log')),
                ('user_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, related_name='returning_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
