# Generated by Django 4.0.3 on 2023-11-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0006_returning'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='returning',
            table='returning',
        ),
    ]
