# Generated by Django 4.0.3 on 2023-11-23 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='No title', max_length=100, null=True)),
                ('field', models.CharField(max_length=500)),
                ('answer', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('hit_count', models.IntegerField(blank=True, default=0)),
                ('user_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, related_name='board_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board',
            },
        ),
    ]
