# Generated by Django 4.0.3 on 2023-11-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_boardmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='title',
            field=models.CharField(blank=True, default='No title', max_length=100),
        ),
    ]
