# Generated by Django 4.0.3 on 2023-11-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_alter_boardmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
