# Generated by Django 4.0.3 on 2023-11-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_alter_boardmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='answer',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
